// AUTO-GENERATED by scripts/sync-backgrounds.mjs — do not edit manually.
// Run: npm run sync-backgrounds

import type { BackgroundCollection } from "@projects/logos-backgrounds/BackgroundCollectionCard";

export const generatedBackgroundCollections: BackgroundCollection[] = [
  {
    "id": "ballon-festival",
    "name": "Ballon Festival",
    "type": "Background Collection",
    "sizes": 5,
    "folder": "Background Collections",
    "color": "#f5a623",
    "thumbnail": "/backgrounds/Ballon%20Festival/1777265338392_8a884e62.jpg",
    "images": {
      "social-1080x1080": "/backgrounds/Ballon%20Festival/1777265296524_9d7c8327.jpg",
      "website-2000x500": "/backgrounds/Ballon%20Festival/1777265334438_2dc05934.jpg",
      "display-300x250": "/backgrounds/Ballon%20Festival/1777265338392_8a884e62.jpg"
    },
    "dimensions": [
      {
        "width": 1080,
        "height": 1080,
        "url": "/backgrounds/Ballon%20Festival/1777265296524_9d7c8327.jpg"
      },
      {
        "width": 2000,
        "height": 500,
        "url": "/backgrounds/Ballon%20Festival/1777265334438_2dc05934.jpg"
      },
      {
        "width": 300,
        "height": 250,
        "url": "/backgrounds/Ballon%20Festival/1777265338392_8a884e62.jpg"
      },
      {
        "width": 1080,
        "height": 1920,
        "url": "/backgrounds/Ballon%20Festival/1777265339543_67a0469a.jpg"
      },
      {
        "width": 1920,
        "height": 1080,
        "url": "/backgrounds/Ballon%20Festival/1777265339547_3890c769.jpg"
      }
    ]
  },
  {
    "id": "beach-sunset",
    "name": "Beach Sunset",
    "type": "Background Collection",
    "sizes": 5,
    "folder": "Background Collections",
    "color": "#e07850",
    "thumbnail": "/backgrounds/Beach%20Sunset/BM_250724_2_DISPLAY_300x250.jpg",
    "images": {
      "display-300x250": "/backgrounds/Beach%20Sunset/BM_250724_2_DISPLAY_300x250.jpg",
      "social-1080x1080": "/backgrounds/Beach%20Sunset/BM_250724_2_SOCIAL_1080x1080.jpg",
      "website-2000x500": "/backgrounds/Beach%20Sunset/BM_250724_2_WEBSITE_2000x500.jpg"
    },
    "dimensions": [
      {
        "width": 1080,
        "height": 1920,
        "url": "/backgrounds/Beach%20Sunset/1777013896250_f3245c0b.jpg"
      },
      {
        "width": 300,
        "height": 250,
        "url": "/backgrounds/Beach%20Sunset/BM_250724_2_DISPLAY_300x250.jpg"
      },
      {
        "width": 1080,
        "height": 1080,
        "url": "/backgrounds/Beach%20Sunset/BM_250724_2_SOCIAL_1080x1080.jpg"
      },
      {
        "width": 1920,
        "height": 1080,
        "url": "/backgrounds/Beach%20Sunset/BM_250724_2_SOCIAL_1080x1080_1920x1080_1768967568271.jpg"
      },
      {
        "width": 2000,
        "height": 500,
        "url": "/backgrounds/Beach%20Sunset/BM_250724_2_WEBSITE_2000x500.jpg"
      }
    ]
  },
  {
    "id": "desert-day",
    "name": "Desert Day",
    "type": "Background Collection",
    "sizes": 8,
    "folder": "Background Collections",
    "color": "#c8a86b",
    "thumbnail": "/backgrounds/Desert%20Day/tmp_b9mipxq_1080x1080_1774762572901_300x250_1774892650125.jpg",
    "images": {
      "social-1080x1080": "/backgrounds/Desert%20Day/tmp_b9mipxq_1080x1080_1774762572901.jpg",
      "display-300x250": "/backgrounds/Desert%20Day/tmp_b9mipxq_1080x1080_1774762572901_300x250_1774892650125.jpg",
      "website-2000x500": "/backgrounds/Desert%20Day/tmp_b9mipxq_2000x500_1774551798555.jpg"
    },
    "dimensions": [
      {
        "width": 1024,
        "height": 1024,
        "url": "/backgrounds/Desert%20Day/tmp_b9mipxq.jpg"
      },
      {
        "width": 1080,
        "height": 1080,
        "url": "/backgrounds/Desert%20Day/tmp_b9mipxq_1080x1080_1774762572901.jpg"
      },
      {
        "width": 300,
        "height": 250,
        "url": "/backgrounds/Desert%20Day/tmp_b9mipxq_1080x1080_1774762572901_300x250_1774892650125.jpg"
      },
      {
        "width": 1080,
        "height": 1920,
        "url": "/backgrounds/Desert%20Day/tmp_b9mipxq_1080x1920_1774551798554.jpg"
      },
      {
        "width": 1440,
        "height": 900,
        "url": "/backgrounds/Desert%20Day/tmp_b9mipxq_1440x900_1774551798576.jpg"
      },
      {
        "width": 1600,
        "height": 900,
        "url": "/backgrounds/Desert%20Day/tmp_b9mipxq_1600x900_1774551798555.jpg"
      },
      {
        "width": 1920,
        "height": 1080,
        "url": "/backgrounds/Desert%20Day/tmp_b9mipxq_1600x900_1774551798555_1920x1080_1774762662987.jpg"
      },
      {
        "width": 2000,
        "height": 500,
        "url": "/backgrounds/Desert%20Day/tmp_b9mipxq_2000x500_1774551798555.jpg"
      }
    ]
  },
  {
    "id": "desert-pyramid-night-sky",
    "name": "Desert Pyramid Night Sky",
    "type": "Background Collection",
    "sizes": 6,
    "folder": "Background Collections",
    "color": "#4a3878",
    "thumbnail": "/backgrounds/Desert%20Pyramid%20Night%20Sky/1777056196506_131012de.jpg",
    "images": {
      "social-1080x1080": "/backgrounds/Desert%20Pyramid%20Night%20Sky/1777056189347_5dacf9b1.jpg",
      "website-2000x500": "/backgrounds/Desert%20Pyramid%20Night%20Sky/1777056196358_e420b6ad.jpg",
      "display-300x250": "/backgrounds/Desert%20Pyramid%20Night%20Sky/1777056196506_131012de.jpg"
    },
    "dimensions": [
      {
        "width": 1080,
        "height": 1080,
        "url": "/backgrounds/Desert%20Pyramid%20Night%20Sky/1777056189347_5dacf9b1.jpg"
      },
      {
        "width": 1080,
        "height": 1920,
        "url": "/backgrounds/Desert%20Pyramid%20Night%20Sky/1777056192917_50fe89c1.jpg"
      },
      {
        "width": 2000,
        "height": 500,
        "url": "/backgrounds/Desert%20Pyramid%20Night%20Sky/1777056196358_e420b6ad.jpg"
      },
      {
        "width": 1920,
        "height": 1080,
        "url": "/backgrounds/Desert%20Pyramid%20Night%20Sky/1777056196467_63249758.jpg"
      },
      {
        "width": 300,
        "height": 250,
        "url": "/backgrounds/Desert%20Pyramid%20Night%20Sky/1777056196506_131012de.jpg"
      },
      {
        "width": 1008,
        "height": 1008,
        "url": "/backgrounds/Desert%20Pyramid%20Night%20Sky/tmpj6dggwm8.jpg"
      }
    ]
  },
  {
    "id": "docks-midday",
    "name": "Docks Midday",
    "type": "Background Collection",
    "sizes": 16,
    "folder": "Background Collections",
    "color": "#5b8db8",
    "thumbnail": "/backgrounds/Docks%20Midday/BM_250515_1_SOCIAL_1080x1080_300x250_1774892650098.jpg",
    "images": {
      "social-1080x1080": "/backgrounds/Docks%20Midday/BM_250515_1_SOCIAL_1080x1080.jpg",
      "display-300x250": "/backgrounds/Docks%20Midday/BM_250515_1_SOCIAL_1080x1080_300x250_1774892650098.jpg",
      "website-2000x500": "/backgrounds/Docks%20Midday/BM_250516_1_WEBSITE_2000x500.jpg",
      "website-600x1067": "/backgrounds/Docks%20Midday/BM_250604_1_STILL_600x1067.jpg",
      "website-600x450": "/backgrounds/Docks%20Midday/BM_250728_1_WEBSITE_600x450.jpg"
    },
    "dimensions": [
      {
        "width": 1080,
        "height": 1080,
        "url": "/backgrounds/Docks%20Midday/BM_250515_1_SOCIAL_1080x1080.jpg"
      },
      {
        "width": 1080,
        "height": 1920,
        "url": "/backgrounds/Docks%20Midday/BM_250515_1_SOCIAL_1080x1080_1080x1920_1776133858467.jpg"
      },
      {
        "width": 1920,
        "height": 1080,
        "url": "/backgrounds/Docks%20Midday/BM_250515_1_SOCIAL_1080x1080_1920x1080_1776133858473.jpg"
      },
      {
        "width": 300,
        "height": 250,
        "url": "/backgrounds/Docks%20Midday/BM_250515_1_SOCIAL_1080x1080_300x250_1774892650098.jpg"
      },
      {
        "width": 2000,
        "height": 500,
        "url": "/backgrounds/Docks%20Midday/BM_250516_1_WEBSITE_2000x500.jpg"
      },
      {
        "width": 1940,
        "height": 500,
        "url": "/backgrounds/Docks%20Midday/BM_250529_1_DISPLAY_970x250.jpg"
      },
      {
        "width": 600,
        "height": 500,
        "url": "/backgrounds/Docks%20Midday/BM_250603_1_STILL_300x250.jpg"
      },
      {
        "width": 600,
        "height": 1200,
        "url": "/backgrounds/Docks%20Midday/BM_250604_1_STILL_300x600.jpg"
      },
      {
        "width": 600,
        "height": 1067,
        "url": "/backgrounds/Docks%20Midday/BM_250604_1_STILL_600x1067.jpg"
      },
      {
        "width": 320,
        "height": 1200,
        "url": "/backgrounds/Docks%20Midday/BM_250613_1_DISPLAY_160x600.jpg"
      },
      {
        "width": 1456,
        "height": 180,
        "url": "/backgrounds/Docks%20Midday/BM_250613_1_DISPLAY_728x90.jpg"
      },
      {
        "width": 1900,
        "height": 776,
        "url": "/backgrounds/Docks%20Midday/BM_250630_1_WEBSITE_1900x776.jpg"
      },
      {
        "width": 800,
        "height": 326,
        "url": "/backgrounds/Docks%20Midday/BM_250725_1_WEBSITE_800x326.jpg"
      },
      {
        "width": 600,
        "height": 450,
        "url": "/backgrounds/Docks%20Midday/BM_250728_1_WEBSITE_600x450.jpg"
      },
      {
        "width": 1440,
        "height": 540,
        "url": "/backgrounds/Docks%20Midday/tmpgwvwccpi.jpg"
      },
      {
        "width": 1440,
        "height": 925,
        "url": "/backgrounds/Docks%20Midday/tmptmf1k1wx.jpg"
      }
    ]
  },
  {
    "id": "field-with-mountain",
    "name": "Field With Mountain",
    "type": "Background Collection",
    "sizes": 6,
    "folder": "Background Collections",
    "color": "#6a9e6a",
    "thumbnail": "/backgrounds/Field%20With%20Mountain/1777014100078_094e3bd4.jpg",
    "images": {
      "display-300x250": "/backgrounds/Field%20With%20Mountain/1777014100078_094e3bd4.jpg",
      "website-2000x500": "/backgrounds/Field%20With%20Mountain/1777014103853_dac91349.jpg",
      "social-1080x1080": "/backgrounds/Field%20With%20Mountain/1777014103877_980b4e71.jpg"
    },
    "dimensions": [
      {
        "width": 300,
        "height": 250,
        "url": "/backgrounds/Field%20With%20Mountain/1777014100078_094e3bd4.jpg"
      },
      {
        "width": 2000,
        "height": 500,
        "url": "/backgrounds/Field%20With%20Mountain/1777014103853_dac91349.jpg"
      },
      {
        "width": 1080,
        "height": 1080,
        "url": "/backgrounds/Field%20With%20Mountain/1777014103877_980b4e71.jpg"
      },
      {
        "width": 1920,
        "height": 1080,
        "url": "/backgrounds/Field%20With%20Mountain/1777014105925_224608eb.jpg"
      },
      {
        "width": 1080,
        "height": 1920,
        "url": "/backgrounds/Field%20With%20Mountain/1777014107932_91d29ba7.jpg"
      },
      {
        "width": 1008,
        "height": 1008,
        "url": "/backgrounds/Field%20With%20Mountain/tmp0vpd_qji.jpg"
      }
    ]
  },
  {
    "id": "forest-lodge",
    "name": "Forest Lodge",
    "type": "Background Collection",
    "sizes": 6,
    "folder": "Background Collections",
    "color": "#5a7a5a",
    "thumbnail": "/backgrounds/Forest%20Lodge/1777217113411_a7cf6a69.jpg",
    "images": {
      "display-300x250": "/backgrounds/Forest%20Lodge/1777217113411_a7cf6a69.jpg",
      "social-1080x1080": "/backgrounds/Forest%20Lodge/1777217113788_5f374958.jpg",
      "website-2000x500": "/backgrounds/Forest%20Lodge/1777217115259_67383756.jpg"
    },
    "dimensions": [
      {
        "width": 300,
        "height": 250,
        "url": "/backgrounds/Forest%20Lodge/1777217113411_a7cf6a69.jpg"
      },
      {
        "width": 1080,
        "height": 1080,
        "url": "/backgrounds/Forest%20Lodge/1777217113788_5f374958.jpg"
      },
      {
        "width": 2000,
        "height": 500,
        "url": "/backgrounds/Forest%20Lodge/1777217115259_67383756.jpg"
      },
      {
        "width": 1080,
        "height": 1920,
        "url": "/backgrounds/Forest%20Lodge/1777217118578_2ecb1bea.jpg"
      },
      {
        "width": 1920,
        "height": 1080,
        "url": "/backgrounds/Forest%20Lodge/1777217119263_b86cc88d.jpg"
      },
      {
        "width": 1008,
        "height": 1008,
        "url": "/backgrounds/Forest%20Lodge/tmpcfcldy8k.jpg"
      }
    ]
  },
  {
    "id": "frozen-lake-night",
    "name": "Frozen Lake Night",
    "type": "Background Collection",
    "sizes": 5,
    "folder": "Background Collections",
    "color": "#8ab4d4",
    "thumbnail": "/backgrounds/Frozen%20Lake%20Night/1777303348542_7657d84b.jpg",
    "images": {
      "social-1080x1080": "/backgrounds/Frozen%20Lake%20Night/1777303258067_2591d360.jpg",
      "website-2000x500": "/backgrounds/Frozen%20Lake%20Night/1777303344664_f6b2740a.jpg",
      "display-300x250": "/backgrounds/Frozen%20Lake%20Night/1777303348542_7657d84b.jpg"
    },
    "dimensions": [
      {
        "width": 1080,
        "height": 1080,
        "url": "/backgrounds/Frozen%20Lake%20Night/1777303258067_2591d360.jpg"
      },
      {
        "width": 2000,
        "height": 500,
        "url": "/backgrounds/Frozen%20Lake%20Night/1777303344664_f6b2740a.jpg"
      },
      {
        "width": 1080,
        "height": 1920,
        "url": "/backgrounds/Frozen%20Lake%20Night/1777303347662_302ab0fa.jpg"
      },
      {
        "width": 300,
        "height": 250,
        "url": "/backgrounds/Frozen%20Lake%20Night/1777303348542_7657d84b.jpg"
      },
      {
        "width": 1920,
        "height": 1080,
        "url": "/backgrounds/Frozen%20Lake%20Night/1777303355700_1e13892e.jpg"
      }
    ]
  },
  {
    "id": "ice-lab",
    "name": "Ice Lab",
    "type": "Background Collection",
    "sizes": 6,
    "folder": "Background Collections",
    "color": "#a0c8e8",
    "thumbnail": "/backgrounds/Ice%20Lab/1777123961113_36260ab2.jpg",
    "images": {
      "display-300x250": "/backgrounds/Ice%20Lab/1777123961113_36260ab2.jpg",
      "social-1080x1080": "/backgrounds/Ice%20Lab/1777123964410_30e18216.jpg",
      "website-2000x500": "/backgrounds/Ice%20Lab/1777217952184_c6ebb98c.jpg"
    },
    "dimensions": [
      {
        "width": 300,
        "height": 250,
        "url": "/backgrounds/Ice%20Lab/1777123961113_36260ab2.jpg"
      },
      {
        "width": 1080,
        "height": 1080,
        "url": "/backgrounds/Ice%20Lab/1777123964410_30e18216.jpg"
      },
      {
        "width": 1080,
        "height": 1920,
        "url": "/backgrounds/Ice%20Lab/1777217951457_369775d6.jpg"
      },
      {
        "width": 2000,
        "height": 500,
        "url": "/backgrounds/Ice%20Lab/1777217952184_c6ebb98c.jpg"
      },
      {
        "width": 1920,
        "height": 1080,
        "url": "/backgrounds/Ice%20Lab/1777217956222_cb32e042.jpg"
      },
      {
        "width": 1008,
        "height": 1008,
        "url": "/backgrounds/Ice%20Lab/tmp3qvkh_ck.jpg"
      }
    ]
  },
  {
    "id": "stadium-night",
    "name": "Stadium Night",
    "type": "Background Collection",
    "sizes": 9,
    "folder": "Background Collections",
    "color": "#2a4a6a",
    "thumbnail": "/backgrounds/Stadium%20Night/BM_250825_1C_Display_300x250.jpg",
    "images": {
      "display-300x250": "/backgrounds/Stadium%20Night/BM_250825_1C_Display_300x250.jpg",
      "display-970x250": "/backgrounds/Stadium%20Night/BM_250825_1C_Display_970x250.jpg",
      "social-1080x1080": "/backgrounds/Stadium%20Night/BM_250825_1C_Social_1080x1080.jpg",
      "website-2000x500": "/backgrounds/Stadium%20Night/BM_250825_1C_Website_2000x500.jpg",
      "website-600x450": "/backgrounds/Stadium%20Night/BM_250825_1C_Website_600x450.jpg"
    },
    "dimensions": [
      {
        "width": 1080,
        "height": 1920,
        "url": "/backgrounds/Stadium%20Night/1777052316983_0d2379ef.jpg"
      },
      {
        "width": 1920,
        "height": 1080,
        "url": "/backgrounds/Stadium%20Night/1777052317533_7bfc6804.jpg"
      },
      {
        "width": 300,
        "height": 250,
        "url": "/backgrounds/Stadium%20Night/BM_250825_1C_Display_300x250.jpg"
      },
      {
        "width": 970,
        "height": 250,
        "url": "/backgrounds/Stadium%20Night/BM_250825_1C_Display_970x250.jpg"
      },
      {
        "width": 1080,
        "height": 1080,
        "url": "/backgrounds/Stadium%20Night/BM_250825_1C_Social_1080x1080.jpg"
      },
      {
        "width": 1920,
        "height": 200,
        "url": "/backgrounds/Stadium%20Night/BM_250825_1C_Website_1920x200.jpg"
      },
      {
        "width": 2000,
        "height": 200,
        "url": "/backgrounds/Stadium%20Night/BM_250825_1C_Website_2000x200.jpg"
      },
      {
        "width": 2000,
        "height": 500,
        "url": "/backgrounds/Stadium%20Night/BM_250825_1C_Website_2000x500.jpg"
      },
      {
        "width": 600,
        "height": 450,
        "url": "/backgrounds/Stadium%20Night/BM_250825_1C_Website_600x450.jpg"
      }
    ]
  },
  {
    "id": "man-walking",
    "name": "Man Walking",
    "type": "Background Collection",
    "sizes": 6,
    "folder": "Background Collections",
    "color": "#2a9d8f",
    "thumbnail": "/backgrounds/Man%20Walking/Man%20Walking.png",
    "images": {
      "banner-300x600": "/backgrounds/Man%20Walking/Man%20Walking.png",
      "banner-160x600": "/backgrounds/Man%20Walking/Man%20Walking-1.png",
      "display-300x250": "/backgrounds/Man%20Walking/Man%20Walking-2.png",
      "banner-728x90": "/backgrounds/Man%20Walking/Man%20Walking-3.png",
      "banner-300x50": "/backgrounds/Man%20Walking/Man%20Walking-4.png",
      "banner-320x50": "/backgrounds/Man%20Walking/Man%20Walking-5.png"
    },
    "dimensions": [
      {
        "width": 300,
        "height": 600,
        "url": "/backgrounds/Man%20Walking/Man%20Walking.png"
      },
      {
        "width": 160,
        "height": 600,
        "url": "/backgrounds/Man%20Walking/Man%20Walking-1.png"
      },
      {
        "width": 300,
        "height": 250,
        "url": "/backgrounds/Man%20Walking/Man%20Walking-2.png"
      },
      {
        "width": 728,
        "height": 90,
        "url": "/backgrounds/Man%20Walking/Man%20Walking-3.png"
      },
      {
        "width": 300,
        "height": 50,
        "url": "/backgrounds/Man%20Walking/Man%20Walking-4.png"
      },
      {
        "width": 320,
        "height": 50,
        "url": "/backgrounds/Man%20Walking/Man%20Walking-5.png"
      }
    ]
  },
  {
    "id": "woman-hiking",
    "name": "Woman Hiking",
    "type": "Background Collection",
    "sizes": 6,
    "folder": "Background Collections",
    "color": "#2a9d8f",
    "thumbnail": "/backgrounds/Woman%20Hiking/Woman%20Hiking.png",
    "images": {
      "banner-300x600": "/backgrounds/Woman%20Hiking/Woman%20Hiking.png",
      "banner-160x600": "/backgrounds/Woman%20Hiking/Woman%20Hiking-1.png",
      "display-300x250": "/backgrounds/Woman%20Hiking/Woman%20Hiking-2.png",
      "banner-728x90": "/backgrounds/Woman%20Hiking/Woman%20Hiking-3.png",
      "banner-300x50": "/backgrounds/Woman%20Hiking/Woman%20Hiking-4.png",
      "banner-320x50": "/backgrounds/Woman%20Hiking/Woman%20Hiking-5.png"
    },
    "dimensions": [
      {
        "width": 300,
        "height": 600,
        "url": "/backgrounds/Woman%20Hiking/Woman%20Hiking.png"
      },
      {
        "width": 160,
        "height": 600,
        "url": "/backgrounds/Woman%20Hiking/Woman%20Hiking-1.png"
      },
      {
        "width": 300,
        "height": 250,
        "url": "/backgrounds/Woman%20Hiking/Woman%20Hiking-2.png"
      },
      {
        "width": 728,
        "height": 90,
        "url": "/backgrounds/Woman%20Hiking/Woman%20Hiking-3.png"
      },
      {
        "width": 300,
        "height": 50,
        "url": "/backgrounds/Woman%20Hiking/Woman%20Hiking-4.png"
      },
      {
        "width": 320,
        "height": 50,
        "url": "/backgrounds/Woman%20Hiking/Woman%20Hiking-5.png"
      }
    ]
  }
];
