import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'Projects': 'Projects',
    'Feeds': 'Feeds',
    'Design': 'Design',
    'Control': 'Control',
    'Campaigns': 'Campaigns',
    'Inventory': 'Inventory',
    'Insights': 'Insights',
    'Tools': 'Tools',
    'AI Tools': 'AI Tools',
    'Search anything': 'Search anything',
    'Funds': 'Funds',
    'Overview': 'Overview',
    'Pre-Approvals': 'Pre-Approvals',
    'Claims': 'Claims',
    'Cases': 'Cases',
    'Generate Report': 'Generate Report',
    'Area': 'Area',
    'All Areas': 'All Areas',
    'Dealership': 'Dealership',
    'All Dealerships': 'All Dealerships',
    'Date Range': 'Date Range',
    'Balance': 'Balance',
    'Current Balance': 'Current Balance',
    'Available Funds': 'Available Funds',
    'Proj. EOY Balance': 'Proj. EOY Balance',
    'Expiring this month': 'Expiring this month',
    'Approved YTD': 'Approved YTD',
    'Avg. Submissions/mo': 'Avg. Submissions/mo',
    'Pending/In Review Claims': 'Pending/In Review Claims',
    'Pending/In-Review Claims': 'Pending/In-Review Claims',
    'Pending/In-Review': 'Pending/In-Review',
    'Payment Status': 'Payment Status',
    'Date': 'Date',
    'Amount': 'Amount',
    'Date paid': 'Date paid',
    'Status': 'Status',
    'Finished': 'Finished',
    'Completed': 'Completed',
    'Available': 'Available',
    'Approved': 'Approved',
    'Pending': 'Pending',
    'Expiring': 'Expiring',
    'Declined': 'Declined',
    'Reimbursed': 'Reimbursed',
    'DMF - Media Costs': 'DMF - Media Costs',
    'DMF - Hard Costs': 'DMF - Hard Costs',
    'DMP - Hard Costs': 'DMP - Hard Costs',
    'Media Costs': 'Media Costs',
    'Media Cost': 'Media Cost',
    'Hard Costs': 'Hard Costs',
    'Hard Cost': 'Hard Cost',
    'Fund utilization': 'Fund utilization',
    'Select Fund': 'Select Fund',
    'Total Balance': 'Total Balance',
    'Breakdown by time in submission phase': 'Breakdown by time in submission phase',
    'Submission – Pre-Approval': 'Submission – Pre-Approval',
    'Pre-Approval – Final Approval': 'Pre-Approval – Final Approval',
    'Final Approval – Payment': 'Final Approval – Payment',
    'Time in Claim phase': 'Time in Claim phase',
    'Claim ID vs days': 'Claim ID vs days',
    'Dealership submission phases vs. days': 'Dealership submission phases vs. days',
    'Claim life cycle': 'Claim life cycle',
    'In days': 'In days',
    'Time in Payment phase': 'Time in Payment phase',
    'Benchmark': 'Benchmark',
    'Benchmark (Avg)': 'Benchmark (Avg)',
    'Average: 7.8': 'Average: 7.8',
    'Average: 8.3': 'Average: 8.3',
    'Accruals': 'Accruals',
    'Submitted': 'Submitted',
    'Year-to-Date': 'Year-to-Date',
    'Avg. Accrual/mo': 'Avg. Accrual/mo',
    'Avg. Submitted/mo': 'Avg. Submitted/mo',
    'Difference': 'Difference',
    'Spend': 'Spend',
    'Accrued funds — by rooftop (USD)': 'Accrued funds — by rooftop (USD)',
    'Accrued Funds — by Region (USD)': 'Accrued Funds — by Region (USD)',
    'Submitted Claims — by Rooftop (Count)': 'Submitted Claims — by Rooftop (Count)',
    'MEDIA - CPO': 'MEDIA - CPO',
    'MEDIA - OTHER': 'MEDIA - OTHER',
    'HARD': 'HARD',
    'Revision Requested': 'Revision Requested',
    'Budget Forecast': 'Budget Forecast',
    '3 months': '3 months',
    '6 months': '6 months',
    '12 months': '12 months',
    '1st semester': '1st semester',
    'Filtering by': 'Filtering by',
    'Clear Filters': 'Clear Filters',
    'Items': 'Items',
    'Show folders': 'Show folders',
    'of': 'of',
    'Goal': 'Goal',
    'Details': 'Details',
    'Cancel': 'Cancel',
    'Submit': 'Submit',
    'Title': 'Title',
    'Dealership Name': 'Dealership Name',
    'Initiative Type': 'Initiative Type',
    'Media Type': 'Media Type',
    'Claim number on this pre-approval': 'Claim number on this pre-approval',
    'Contact Information': 'Contact Information',
    'Supporting Documents': 'Supporting Documents',
    'Select Dealership': 'Select Dealership',
    'Select Initiative': 'Select Initiative',
    'Select Media Type': 'Select Media Type',
    'Approval Request': 'Approval Request',
    'Last updated': 'Last updated',
    'Submitted at': 'Submitted at',
    'Submitted by': 'Submitted by',
    'How many claims will you be making': 'How many claims will you be making',
    'MEDIA TYPE': 'MEDIA TYPE',
    'Description': 'Description',
    'No documents attached': 'No documents attached',
    'Revisions Required': 'Revisions Required',
    'Review Pre-approval request': 'Review Pre-approval request',
    'Id': 'Id',
    'Comment': 'Comment',
    'Send': 'Send',
    'Add your comments here...': 'Add your comments here...',
    'Follow': 'Follow',
    'Compliance Team': 'Compliance Team',
    'Pre-approval': 'Pre-approval',
    // Status chips
    'Open': 'Open',
    'In Review': 'In Review',
    'Penalty Applied': 'Penalty Applied',
    'Denied': 'Denied',
    // ClaimsPanel
    'Claim Overview': 'Claim Overview',
    'Date Submitted': 'Date Submitted',
    'Fund': 'Fund',
    'Type': 'Type',
    'Time in Claim': 'Time in Claim',
    'Time in Payment': 'Time in Payment',
    'No additional details provided for this claim.': 'No additional details provided for this claim.',
    'Documents': 'Documents',
    'Process Payment': 'Process Payment',
    // FundsClaimsContent
    'New Claim': 'New Claim',
    'Find below': 'Find below',
    'Month': 'Month',
    'Accrual': 'Accrual',
    'Submission': 'Submission',
    'Paid': 'Paid',
    'Time in claim': 'Time in claim',
    'Time in payment': 'Time in payment',
    // FundsPreApprovalsContent
    'New Pre-Approval': 'New Pre-Approval',
    'Time in Pre-approval': 'Time in Pre-approval',
    'Last Updated': 'Last Updated',
    'No pre-approvals found matching your criteria.': 'No pre-approvals found matching your criteria.',
    // CasesTab / FundsCasesContent
    'New Case': 'New Case',
    'Search cases': 'Search cases',
    'Case ID': 'Case ID',
    'Date Opened': 'Date Opened',
    'Priority': 'Priority',
    'Assigned To': 'Assigned To',
    'Last Activity': 'Last Activity',
    'ID': 'ID',
    // GenerateReportMenu
    'Fund Utilization Report': 'Fund Utilization Report',
    'Fund Allocation Report': 'Fund Allocation Report',
    'Fund Usage Report': 'Fund Usage Report',
    'Claim Submission Report': 'Claim Submission Report',
    'Pre-approval Summary Report': 'Pre-approval Summary Report',
    'Payment Processing Report': 'Payment Processing Report',
    // DateRangePicker
    'SELECT DATE RANGE': 'SELECT DATE RANGE',
    'This Week': 'This Week',
    'Last Week': 'Last Week',
    'Last 7 Days': 'Last 7 Days',
    'Current Month': 'Current Month',
    'Next Month': 'Next Month',
    'Reset': 'Reset',
    'Ok': 'Ok',
    // BudgetForecastRangeTabs
    '3 Months': '3 Months',
    '6 Months': '6 Months',
    '12 Months': '12 Months',
    // WebMonitoringContent
    'Detected On': 'Detected On',
    'Violation Type': 'Violation Type',
    'Website / URL': 'Website / URL',
    'Severity': 'Severity',
    'No violations found matching your criteria.': 'No violations found matching your criteria.',
    // WebMonitoringPanel + Modal
    'Website Compliance Case': 'Website Compliance Case',
    'Violation Details': 'Violation Details',
    'Channel': 'Channel',
    'Issue Preview': 'Issue Preview',
    'Annotated evidence captured from the monitored dealership page.': 'Annotated evidence captured from the monitored dealership page.',
    'Assign Penalty': 'Assign Penalty',
    'Mark As Reviewed': 'Mark As Reviewed',
    // AppContent tabs
    'Planner': 'Planner',
    'Guidelines & Assets': 'Guidelines & Assets',
    'Web Monitoring': 'Web Monitoring',
    // PaymentStatusTableCard
    'Payouts': 'Payouts',
    // FundsCasesContent — filter & type/priority cells
    'Case Type': 'Case Type',
    'All Types': 'All Types',
    'All Priorities': 'All Priorities',
    'Resolved': 'Resolved',
    'Escalated': 'Escalated',
    'High': 'High',
    'Medium': 'Medium',
    'Low': 'Low',
    'Audit': 'Audit',
    'Dispute': 'Dispute',
    'Compliance': 'Compliance',
    // PaymentStatusTable
    'Paid out': 'Paid out',
    // DateRangePicker fallback
    'Select Range': 'Select Range',
    // WebMonitoringPanel / Modal — annotation strings
    'Missing Legal Disclaimer': 'Missing Legal Disclaimer',
    'Offer card displays payment terms without required disclaimer language visible near the promotional copy.': 'Offer card displays payment terms without required disclaimer language visible near the promotional copy.',
    // WebMonitoringContent table
    'Showing 10 violations': 'Showing 10 violations',
    // WebMonitoringPanel channel value
    'Website': 'Website',
    // Misc
    'Claim': 'Claim',
  },
  fr: {
    'Projects': 'Projets',
    'Feeds': 'Flux',
    'Design': 'Design',
    'Control': 'Contrôle',
    'Campaigns': 'Campagnes',
    'Inventory': 'Inventaire',
    'Insights': 'Analyses',
    'Tools': 'Outils',
    'AI Tools': 'Outils IA',
    'Search anything': 'Rechercher',
    'Funds': 'Fonds',
    'Overview': 'Aperçu',
    'Pre-Approvals': 'Préautorisations',
    'Claims': 'Réclamations',
    'Cases': 'Dossiers',
    'Generate Report': 'Générer un rapport',
    'Area': 'Zone',
    'All Areas': 'Toutes les zones',
    'Dealership': 'Concessionnaire',
    'All Dealerships': 'Tous les concessionnaires',
    'Date Range': 'Plage de dates',
    'Balance': 'Solde',
    'Current Balance': 'Solde actuel',
    'Available Funds': 'Fonds disponibles',
    'Proj. EOY Balance': 'Solde projeté fin d\'année',
    'Expiring this month': 'Expire ce mois-ci',
    'Approved YTD': 'Approuvé à ce jour',
    'Avg. Submissions/mo': 'Moy. soumissions/mois',
    'Pending/In Review Claims': 'Réclamations en attente / en révision',
    'Pending/In-Review Claims': 'Réclamations en attente / en révision',
    'Pending/In-Review': 'En attente / en révision',
    'Payment Status': 'Statut des paiements',
    'Date': 'Date',
    'Amount': 'Montant',
    'Date paid': 'Date de paiement',
    'Status': 'Statut',
    'Finished': 'Terminé',
    'Completed': 'Terminé',
    'Available': 'Disponible',
    'Approved': 'Approuvé',
    'Pending': 'En attente',
    'Expiring': 'Expire',
    'Declined': 'Refusé',
    'Reimbursed': 'Remboursé',
    'DMF - Media Costs': 'DMF - Coûts médias',
    'DMF - Hard Costs': 'DMF - Coûts directs',
    'DMP - Hard Costs': 'DMP - Coûts directs',
    'Media Costs': 'Coûts médias',
    'Media Cost': 'Coûts médias',
    'Hard Costs': 'Coûts directs',
    'Hard Cost': 'Coûts directs',
    'Fund utilization': 'Utilisation des fonds',
    'Select Fund': 'Sélectionner',
    'Total Balance': 'Solde total',
    'Breakdown by time in submission phase': 'Temps par étape de soumission',
    'Submission – Pre-Approval': 'Soumission – Préautorisation',
    'Pre-Approval – Final Approval': 'Préautorisation – Approbation finale',
    'Final Approval – Payment': 'Approbation finale – Paiement',
    'Time in Claim phase': 'Délai des réclamations',
    'Claim ID vs days': 'ID de réclamation (jours)',
    'Dealership submission phases vs. days': 'Délai par étape de soumission',
    'Claim life cycle': 'Cycle de vie des réclamations',
    'In days': 'En jours',
    'Time in Payment phase': 'Délai des paiements',
    'Benchmark': 'Référence',
    'Benchmark (Avg)': 'Référence (Moy.)',
    'Average: 7.8': 'Moy. : 7,8',
    'Average: 8.3': 'Moy. : 8,3',
    'Accruals': 'Dépenses engagées',
    'Submitted': 'Soumis',
    'Year-to-Date': 'Cumul annuel',
    'Avg. Accrual/mo': 'Moy. charges/mois',
    'Avg. Submitted/mo': 'Moy. soumis/mois',
    'Difference': 'Écart',
    'Spend': 'Dépenses',
    'Accrued funds — by rooftop (USD)': 'Fonds engagés — par concessionnaire (USD)',
    'Accrued Funds — by Region (USD)': 'Fonds engagés — par région (USD)',
    'Submitted Claims — by Rooftop (Count)': 'Réclamations soumises — par concessionnaire',
    'MEDIA - CPO': 'Média – CPO',
    'MEDIA - OTHER': 'Média – Autres',
    'HARD': 'Coûts directs',
    'Revision Requested': 'Révision requise',
    'Budget Forecast': 'Prévision budgétaire',
    '3 months': '3 mois',
    '6 months': '6 mois',
    '12 months': '12 mois',
    '1st semester': '1er semestre',
    'Filtering by': 'Filtrer par',
    'Clear Filters': 'Réinitialiser les filtres',
    'Items': 'Éléments',
    'Show folders': 'Afficher les dossiers',
    'of': 'sur',
    'Goal': 'Objectif',
    'Find below': 'Rechercher',
    'Details': 'Détails',
    'Cancel': 'Annuler',
    'Submit': 'Soumettre',
    'Title': 'Titre',
    'Dealership Name': 'Nom de la concession',
    'Initiative Type': 'Type d\'initiative',
    'Media Type': 'Type de média',
    'Claim number on this pre-approval': 'Nombre de réclamations sur cette préautorisation',
    'Contact Information': 'Informations de contact',
    'Supporting Documents': 'Documents justificatifs',
    'Select Dealership': 'Sélectionner une concession',
    'Select Initiative': 'Sélectionner une initiative',
    'Select Media Type': 'Sélectionner le type de média',
    'Approval Request': 'Demande d\'approbation',
    'Last updated': 'Dernière mise à jour',
    'Submitted at': 'Soumis le',
    'Submitted by': 'Soumis par',
    'How many claims will you be making': 'Nombre de réclamations prévues',
    'MEDIA TYPE': 'TYPE DE MÉDIA',
    'Description': 'Description',
    'No documents attached': 'Aucun document joint',
    'Revisions Required': 'Révisions requises',
    'Review Pre-approval request': 'Réviser la demande de préautorisation',
    'Id': 'Id',
    'Comment': 'Commentaire',
    'Send': 'Envoyer',
    'Add your comments here...': 'Ajoutez vos commentaires ici...',
    'Follow': 'Suivre',
    'Compliance Team': 'Équipe de conformité',
    'Pre-approval': 'Préautorisation',
    // Status chips
    'Open': 'Ouvert',
    'In Review': 'En révision',
    'Penalty Applied': 'Pénalité appliquée',
    'Denied': 'Refusé',
    // ClaimsPanel
    'Claim Overview': 'Aperçu de la réclamation',
    'Date Submitted': 'Date de soumission',
    'Fund': 'Fonds',
    'Type': 'Type',
    'Time in Claim': 'Délai de réclamation',
    'Time in Payment': 'Délai de paiement',
    'No additional details provided for this claim.': 'Aucun détail supplémentaire pour cette réclamation.',
    'Documents': 'Documents',
    'Process Payment': 'Traiter le paiement',
    // FundsClaimsContent
    'New Claim': 'Nouvelle réclamation',
    'Month': 'Mois',
    'Accrual': 'Charges engagées',
    'Submission': 'Soumission',
    'Paid': 'Payé',
    'Time in claim': 'Délai de réclamation',
    'Time in payment': 'Délai de paiement',
    // FundsPreApprovalsContent
    'New Pre-Approval': 'Nouvelle préautorisation',
    'Time in Pre-approval': 'Délai de préautorisation',
    'Last Updated': 'Dernière mise à jour',
    'No pre-approvals found matching your criteria.': 'Aucune préautorisation ne correspond à vos critères.',
    // CasesTab / FundsCasesContent
    'New Case': 'Nouveau dossier',
    'Search cases': 'Rechercher des dossiers',
    'Case ID': 'ID de dossier',
    'Date Opened': "Date d'ouverture",
    'Priority': 'Priorité',
    'Assigned To': 'Assigné à',
    'Last Activity': 'Dernière activité',
    'ID': 'ID',
    // GenerateReportMenu
    'Fund Utilization Report': "Rapport d'utilisation des fonds",
    'Fund Allocation Report': "Rapport d'allocation des fonds",
    'Fund Usage Report': "Rapport d'usage des fonds",
    'Claim Submission Report': 'Rapport de soumission des réclamations',
    'Pre-approval Summary Report': 'Rapport sommaire des préautorisations',
    'Payment Processing Report': 'Rapport de traitement des paiements',
    // DateRangePicker
    'SELECT DATE RANGE': 'SÉLECTIONNER UNE PLAGE DE DATES',
    'This Week': 'Cette semaine',
    'Last Week': 'Semaine dernière',
    'Last 7 Days': '7 derniers jours',
    'Current Month': 'Mois en cours',
    'Next Month': 'Mois prochain',
    'Reset': 'Réinitialiser',
    'Ok': 'Ok',
    // BudgetForecastRangeTabs
    '3 Months': '3 mois',
    '6 Months': '6 mois',
    '12 Months': '12 mois',
    // WebMonitoringContent
    'Detected On': 'Détecté le',
    'Violation Type': 'Type de violation',
    'Website / URL': 'Site web / URL',
    'Severity': 'Gravité',
    'No violations found matching your criteria.': 'Aucune violation ne correspond à vos critères.',
    // WebMonitoringPanel + Modal
    'Website Compliance Case': 'Dossier de conformité web',
    'Violation Details': 'Détails de la violation',
    'Channel': 'Canal',
    'Issue Preview': 'Aperçu du problème',
    'Annotated evidence captured from the monitored dealership page.': 'Preuves annotées capturées depuis la page du concessionnaire surveillé.',
    'Assign Penalty': 'Attribuer une pénalité',
    'Mark As Reviewed': 'Marquer comme révisé',
    // AppContent tabs
    'Planner': 'Planificateur',
    'Guidelines & Assets': 'Directives et actifs',
    'Web Monitoring': 'Surveillance web',
    // PaymentStatusTableCard
    'Payouts': 'Paiements',
    // FundsCasesContent — filter & type/priority cells
    'Case Type': 'Type de dossier',
    'All Types': 'Tous les types',
    'All Priorities': 'Toutes les priorités',
    'Resolved': 'Résolu',
    'Escalated': 'Escaladé',
    'High': 'Élevée',
    'Medium': 'Moyenne',
    'Low': 'Faible',
    'Audit': 'Audit',
    'Dispute': 'Contestation',
    'Compliance': 'Conformité',
    // PaymentStatusTable
    'Paid out': 'Versé',
    // DateRangePicker fallback
    'Select Range': 'Sélectionner une plage',
    // WebMonitoringPanel / Modal — annotation strings
    'Missing Legal Disclaimer': 'Avertissement légal manquant',
    'Offer card displays payment terms without required disclaimer language visible near the promotional copy.': 'La carte d\'offre affiche des conditions de paiement sans l\'avertissement légal requis visible près du texte promotionnel.',
    // WebMonitoringContent table
    'Showing 10 violations': '10 violations affichées',
    // WebMonitoringPanel channel value
    'Website': 'Site web',
    // Misc
    'Claim': 'Réclamation',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    if (!key) return '';
    const langTranslations = translations[language];
    if (!langTranslations) return key;
    return langTranslations[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
